require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

AllCops:
  Exclude:
    - url_slug.gemspec
